### ISSUE TITLE
Strange rendering of a-minus primitives after setting different alpha-values

### ISSUE THREAD

**Issue by acl-crypto** [decentraland/sdk-issues#5]
I made a scene with a-minus-primitives and lots of different alpha-settings. Now there are strange opacity effects. Sometimes it works (looking "through" a window) and sometimes (depending on the "looking angle") I see "through" different walls, see pictures hanging inside a room from the outside and so on....
See video on discord-channel ("support-SDK"-channel)

**Comment by belohlavek** [comment]
https://cdn.discordapp.com/attachments/437689723020902410/469204081387372546/Decentraland_Preview_alpha-problem.mp4

**Comment by menduz** [comment]
@deltakosh any idea about how to workaround this?

**Comment by deltakosh** [comment]
Is this with Babylon.js? Looks weird. We have several tools to sort meshes based on distance to camera.

Unless all meshes are transparent? And then the way to fix it would be to make as transparent only the transparent meshes

**Comment by acl-crypto** [comment]
Maybe that helps:
I mainly used boxes for the scene (to save vertices/triangles). So actually (almost) everything is boxes on top of another box (e.g. picture-frame(-box) on top of the wall(-box)).

One of my window-tsx-files looks like this:
(see picture)
![prob180718](https://user-images.githubusercontent.com/35429203/42902817-2009e72c-8ad0-11e8-8cfa-5b59ff6a29a9.jpg)

My materials are defined in the scene.tsx-file (to keep an overview regarding material-limits):
  		<material id="Stone02" alpha={1} albedoTexture={'/textures/stone02.jpg'}/>
		<material id="glasseffect" alpha={0.3} albedoTexture={'/textures/glass.jpg'} />
		<material id="woodeffect" alpha={1} albedoTexture={'/textures/wood.jpg'} />
		<material id="woodeffect01" alpha={1} albedoTexture={'/textures/wood1.jpg'}/>

**Comment by menduz** [comment]
@deltakosh thanks. We are setting opacityTexture = albedoTexture by default. Will drop that behavior

**Comment by deltakosh** [comment]
Definitely the issue here;)

**Comment by menduz** [comment]
Please test using metaverse-api@next

We added `<material hasAlpha={true} />` to enable alpha in textures

**Comment by menduz** [comment]
@acl-crypto

**Comment by acl-crypto** [comment]
@menduz After npm install metaverse-api@next I have an older api now (metaverse-api version: 4.0.0-20180718211325.commit-70f72bb (OUTDATED)). It was version 4.0.2 before.
Problem still the same. Scene movement even worse.
Should i try: npm install metaverse-api@latest ?

**Comment by menduz** [comment]
can you share a video ?

**Comment by acl-crypto** [comment]
@menduz It`s still like this: https://cdn.discordapp.com/attachments/437689723020902410/469204081387372546/Decentraland_Preview_alpha-problem.mp4

**Comment by menduz** [comment]
We need to see the difference video, that part you say it is worse. Or a zip with your example or a reproduction to debug the problem.

**Comment by acl-crypto** [comment]
@menduz : I doublechecked it: Sorry, the movement problems (kind of "jerky movement") were a Firefox-browser issue. In Chrome the movement is OK like before:

So summary:
OS: Windows 10, Browser: Chrome
Before: metaverse-api 4.0.2, strange alpha/opacity-issues like in the video (see link above).
After _npm install metaverse-api(at)next_: metaverse-api version: 4.0.0-20180718211325.commit-70f72bb (OUTDATED), still exactly the same opacity issues at the same angles/views. (Btw. i can go "through" walls now. ingoreCollision effect?)
I made another video but it looks exactly the same like the old one

**Comment by menduz** [comment]
Ohh, well, we are going to need a reproduction zip to debug it. Can you provide at least a subset of your use case to test?

About `ingoreCollision`: we are changing it to `withCollisions={true}` for performance reasons and consistency with gltf/obj models

**Comment by acl-crypto** [comment]
@menduz I sent an Email to your github profile address

**Comment by acl-crypto** [comment]
@menduz There's another way to get this error/bug. Even without using alpha={1}:
When I use a "normal" material (without loading anything) like:
`<material id="metallic" metallic={0.5} roughness={0.1} />
<plane scale={{ x: 1, y: 1, z: 1 }} position={{ x: 0, y: 0, z: 0 }} rotation={{ x: 0, y: 0, z: 0 }} color="#FFFFFF" material="#metallic" />`
.... then everything is fine.
When I load a file as texture like:
`<material id="chrome" albedoTexture={'/textures/chrome.jpg'} alphaTexture={'/textures/chrome.jpg'} />
<plane scale={{ x: 1, y: 1, z: 1 }} position={{ x: 0, y: 0, z: 0 }} rotation={{ x: 0, y: 0, z: 0 }} color="#FFFFFF" material="#chrome" />`
.... I get the same strange opacity-effects (things disappearing related to view angle, seeing things through walls, etc.)

**Comment by menduz** [comment]
@acl-crypto please remove the `alphaTexture` from your materials and tell me if it works

**Comment by acl-crypto** [comment]
@menduz
I deleted just the "main" texture (of the wall) and the scene works (even if I keep the other textures)
See:
With texture:
https://cdn.discordapp.com/attachments/437689723020902410/472667285056782347/texture_bug_report_01.mp4
Without texture:
https://cdn.discordapp.com/attachments/437689723020902410/472667367592165386/texture_bug_report_02.mp4

**Comment by menduz** [comment]
when you say `main` are you talking about the albedo texture?

**Comment by acl-crypto** [comment]
I have/had 9 materials. All with different _alpha_, _albedoTexture_ and _alphaTexture_. I only deleted **one** of these textures (the texture of all of the walls .... see videos before and after deleting this one texture) .... and then it worked !
